/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : AFE_FRST.H
**     Project   : CyberNT3
**     Processor : 56F8366
**     Component : BitIO
**     Version   : Component 02.075, Driver 01.18, CPU db: 2.87.042
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2011/8/20, 22:03
**     Abstract  :
**         This bean "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This bean is set to work in Output direction only.
**         Methods of this bean are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       46            |  GPIOD8_PSB_CS0B
**             ----------------------------------------------------
**
**         Port name                   : GPIOD_High
**
**         Bit number (in port)        : 8
**         Bit mask of the port        : 256
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : GPIO_D_DR [62241]
**         Port control register       : GPIO_D_DDR [62242]
**         Port function register      : GPIO_D_PER [62243]
**
**         Optimization for            : speed
**     Contents  :
**         ClrVal - void AFE_FRST_ClrVal(void);
**         SetVal - void AFE_FRST_SetVal(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __AFE_FRST_H
#define __AFE_FRST_H

/* MODULE AFE_FRST. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "PE_Timer.h"

#include "Cpu.h"


#define AFE_FRST_PIN_MASK       ((word)256) /* Pin mask */
#define AFE_FRST_PIN_MASK_SHIFTED ((byte)1) /* Shifted pin mask by 8, if pin mask is greater than 128 */


/*
** ===================================================================
**     Method      :  AFE_FRST_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define AFE_FRST_ClrVal() (clrRegBits(GPIO_D_DR,AFE_FRST_PIN_MASK))

/*
** ===================================================================
**     Method      :  AFE_FRST_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define AFE_FRST_SetVal() (setRegBits(GPIO_D_DR,AFE_FRST_PIN_MASK))


/* END AFE_FRST. */

#endif /* __AFE_FRST_H*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
