/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : AFE_I2C.C
**     Project   : CyberNT3
**     Processor : 56F8366
**     Component : SW_I2C
**     Version   : Component 01.121, Driver 03.27, CPU db: 2.87.042
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2011/8/20, 22:03
**     Abstract  :
**         This device "SW_I2C" implements an external I2C
**         communication interface. It uses two general-purpose
**         I/O pins.
**     Settings  :
**         Serial Clock (SCL) pin      :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       53            |  GPIOD12_ISB2
**             ----------------------------------------------------
**
**         Serial Data (SDA) pin       :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       52            |  GPIOD11_ISB1
**             ----------------------------------------------------
**
**
**         Mode                        : MASTER
**         Communication Speed         : FAST MODE
**         Output Buffer Size          : 0
**         Auto Stop Condition         : yes
**         Acknowledge Polling Trials  : 2000
**
**         Speed modes
**
**             High Speed Mode         : Enabled
**             Low Speed Mode          : Disabled
**             Slow Speed Mode         : Disabled
**
**         Initialization
**
**             Slave address           : 92
**             Bean function           : Enabled
**             Events                  : Enabled
**     Contents  :
**         SendBlock   - byte AFE_I2C_SendBlock(void* Ptr, word Siz, word *Snt);
**         SelectSlave - byte AFE_I2C_SelectSlave(byte Slv);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


/* MODULE AFE_I2C. */

#include "PE_Error.h"
#include "AFE_I2C.h"
#include "Inhr5.h"
#include "Inhr4.h"


#define ACK         0
#define NOACK       1
#define OUTPUT      1
#define INPUT       0
#define WRITE       0
#define READ        1
#define TRIALS      2000

static byte SlaveAddr;             /* destination slave address      */

/* Internal method prototypes */
/*
** ===================================================================
**     Method      :  AFE_I2C_Delay (component SW_I2C)
**
**     Description :
**         The method waits in delay loop.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void Delay(void)
{
  asm {
    /*
     * Delay
     *   - requested                  : 1250 ns @ 80MHz,
     *   - possible                   : 100 c, 1250 ns
     */
    adda #2, SP                        /* (1 c: 12.5 ns) move SP forward */
    move.l A10, X:(SP)                 /* (2 c: 25 ns) push A */
    move.w #42, A                      /* (2 c: 25 ns) number of iterations */
    do A, label0                       /* (8 c: 100 ns) repeat 42x nop */
      nop                              /* (1 c: 12.5 ns) wait for 1 c */
    label0:
    move.l X:(SP), A                   /* (2 c: 25 ns) pop A */
    suba #2, SP                        /* (1 c: 12.5 ns) move SP back */
  }
}

/*
** ===================================================================
**     Method      :  AFE_I2C_Init (component SW_I2C)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void AFE_I2C_Init(void)
{
  SlaveAddr = 184;
}

/*
** ===================================================================
**     Method      :  AFE_I2C_Write (component SW_I2C)
**
**     Description :
**         The method sends one byte of data to the bus.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void Write(byte Data)
{
  byte Shift;
  byte I;
  word timeout;

  Shift = 128;
  for (I = 8; I != 0; I--) {
    if (Data & Shift) {
      Inhr4_SetDir((bool)INPUT);   /* SDA HIGH */
    }
    else {
      Inhr4_SetDir((bool)OUTPUT);
      Inhr4_ClrVal();              /* SDA LOW */
    }
    Shift >>= 1;
    Inhr5_SetDir((bool)INPUT);     /* CLOCK HIGH PULSE */
    Delay();
    timeout = 65535;
    while((Inhr5_GetVal()==0)&&(timeout!=0)) { /* WAIT FOR CLOCK HIGH PULSE */
      timeout--;
    }
    Inhr5_SetDir((bool)OUTPUT);
    Inhr5_ClrVal();                /* CLOCK LOW PULSE */
    Delay();
  }
}

/*
** ===================================================================
**     Method      :  AFE_I2C_GetAck (component SW_I2C)
**
**     Description :
**         The method reads ACK from the bus.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static bool GetAck(void)
{
  word timeout;

  Inhr4_SetDir((bool)INPUT);       /* SDA HIGH */
  Inhr5_SetDir((bool)INPUT);       /* CLOCK HIGH PULSE */
  Delay();
  timeout = 65535;
  while((Inhr5_GetVal()==0)&&(timeout!=0)) { /* WAIT FOR CLOCK HIGH PULSE */
    timeout--;
  }
  return((bool)Inhr4_GetVal());    /* ACKNOWLEDGE VALUE */
}

/*
** ===================================================================
**     Method      :  AFE_I2C_InternalStop (component SW_I2C)
**
**     Description :
**         The method generates the Stop condition on the bus.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void InternalStop(void)
{
  Inhr4_SetDir((bool)OUTPUT);
  Inhr4_ClrVal();                  /* STOP SETUP */
  Inhr5_SetDir((bool)INPUT);       /* CLOCK HIGH PULSE + STOP SETUP TIME */
  Delay();
  Inhr4_SetDir((bool)INPUT);       /* STOP CONDITION */
}

/*
** ===================================================================
**     Method      :  AFE_I2C_SendBlock (component SW_I2C)
**
**     Description :
**         When working as a MASTER, this method writes 7 bits of slave
**         address plus R/W bit = 0 to the I2C bus and then writes the
**         block of characters to the bus. If the bean is disabled (by
**         the "Disable" method or initialization), the block is moved
**         to the output buffer if the <Output buffer size> property is
**         different from zero. The content of the output buffer is
**         sent immediately with the stop condition at the end when the
**         bean is enabled by the "Enable" method. After the output
**         buffer transmission, the whole output buffer is cleared. The
**         slave address must be specified before by the "SelectSlave"
**         method or in bean initialization section of <Slave address
**         init> property. When working as a SLAVE, this method writes
**         block of characters to the bus. If the ERR_NOTAVAIL error
**         code is returned, the whole block is successfully sent to a
**         master but the master device responds by an acknowledgement
**         instead of no acknowledgment sent at the end of the last
**         block byte transfer. <OnError> event is called in this case.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - A pointer to the block of data to send
**         Siz             - The size of the block
**       * Snt             - A pointer to the number of data that are
**                           sent (copied to buffer)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_BUSY - The slave device is busy, it
**                           does not respond by the acknowledgement
**                           (MASTER mode only)
**                           ERR_TXFULL - Output buffer is full (MASTER
**                           mode only)
**                           ERR_NOTAVAIL - The master device sends
**                           acknowledgement instead of no
**                           acknowledgement after the last byte
**                           transfer (SLAVE mode only)
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSOFF - Clock timeout elapsed (SLAVE
**                           mode only)
** ===================================================================
*/
byte AFE_I2C_SendBlock(void* Ptr,word Siz,word *Snt)
{
  register word I;
  bool Acknowledge;
  word Trial;

  *Snt = 0;
  Trial = TRIALS;
  do {
    Inhr4_SetDir((bool)INPUT);     /* SDA HIGH  - START SETUP */
    Inhr5_SetDir((bool)INPUT);     /* CLOCK HIGH PULSE */
    Delay();                       /* CLOCK HIGH PULSE + BUS FREE TIME */
    Inhr4_SetDir((bool)OUTPUT);
    Inhr4_ClrVal();                /* START CONDITION */
    Delay();                       /* START HOLD TIME */
    Inhr5_SetDir((bool)OUTPUT);
    Inhr5_ClrVal();                /* CLOCK LOW PULSE */
    Delay();
    Write((byte)(SlaveAddr + WRITE));
    Acknowledge = GetAck();
    --Trial;
  } while (Trial && Acknowledge);
  if (Acknowledge) {
    Inhr5_SetDir((bool)OUTPUT);
    Inhr5_ClrVal();                /* CLOCK LOW PULSE */
    InternalStop();
    return ERR_BUSY;
  }
  else {
    Inhr5_SetDir((bool)OUTPUT);
    Inhr5_ClrVal();                /* CLOCK LOW PULSE */
    Delay();
  }
  for (I = 0; I < Siz; I++) {
    Write ( *((byte *) Ptr + I) );
    if (GetAck()) {
      Inhr5_SetDir((bool)OUTPUT);
      Inhr5_ClrVal();              /* CLOCK LOW PULSE */
      InternalStop();
      return ERR_BUSY;
    }
    else {
      Inhr5_SetDir((bool)OUTPUT);
      Inhr5_ClrVal();              /* CLOCK LOW PULSE */
      Delay();
    }
    ++(*Snt);
  }
  InternalStop();
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  AFE_I2C_SelectSlave (component SW_I2C)
**
**     Description :
**         When working as a MASTER, this method selects a new slave
**         for communication by its slave address value. Any send or
**         receive method are directed to or from the selected device,
**         until a new slave device is selected by this method. If the
**         selected slave uses 10-bit slave addressing, as the
**         parameter 7 bits must be passed, which involves 10-bit
**         addressing (11110XX), including two MSBs of slave address
**         (XX). The second byte of the 10-bit slave address must be
**         sent to the slave as a general character of send methods.
**         This method is available only if the bean is in MASTER mode.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Slv             - Slave address value
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED -  Device is disabled
** ===================================================================
*/
byte AFE_I2C_SelectSlave(byte Slv)
{
  SlaveAddr = (byte)(Slv << 1);
  return ERR_OK;
}


/* END AFE_I2C. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
