/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : BATT.C
**     Project   : CyberNT3
**     Processor : 56F8366
**     Component : ADC
**     Version   : Component 01.580, Driver 02.05, CPU db: 2.87.042
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2011/8/20, 22:03
**     Abstract  :
**         This device "ADC" implements an A/D converter,
**         its control methods and interrupt/event handling procedure.
**     Settings  :
**         AD control register         : ADCA_ADCR1  [61952]
**         AD control register         : ADCA_ADCR2  [61953]
**         AD control register         : ADCA_ADZCC  [61954]
**         AD control register         : ADCA_ADLST1 [61955]
**         AD control register         : ADCA_ADLST2 [61956]
**         AD control register         : ADCA_ADSDIS [61957]
**         AD control register         : ADCA_ADSTAT [61958]
**         AD control register         : ADCA_ADLSTAT [61959]
**         AD control register         : ADCA_ADZCSTAT [61960]
**         AD control register         : ADCA_ADLLMT0 [61969]
**         AD control register         : ADCA_ADLLMT1 [61970]
**         AD control register         : ADCA_ADLLMT2 [61971]
**         AD control register         : ADCA_ADLLMT3 [61972]
**         AD control register         : ADCA_ADLLMT4 [61973]
**         AD control register         : ADCA_ADLLMT5 [61974]
**         AD control register         : ADCA_ADLLMT6 [61975]
**         AD control register         : ADCA_ADLLMT7 [61976]
**         AD control register         : ADCA_ADHLMT0 [61977]
**         AD control register         : ADCA_ADHLMT1 [61978]
**         AD control register         : ADCA_ADHLMT2 [61979]
**         AD control register         : ADCA_ADHLMT3 [61980]
**         AD control register         : ADCA_ADHLMT4 [61981]
**         AD control register         : ADCA_ADHLMT5 [61982]
**         AD control register         : ADCA_ADHLMT6 [61983]
**         AD control register         : ADCA_ADHLMT7 [61984]
**         AD control register         : ADCA_ADOFS0 [61985]
**         AD control register         : ADCA_ADOFS1 [61986]
**         AD control register         : ADCA_ADOFS2 [61987]
**         AD control register         : ADCA_ADOFS3 [61988]
**         AD control register         : ADCA_ADOFS4 [61989]
**         AD control register         : ADCA_ADOFS5 [61990]
**         AD control register         : ADCA_ADOFS6 [61991]
**         AD control register         : ADCA_ADOFS7 [61992]
**         AD control register         : ADCA_ADPOWER [61993]
**         AD control register         : ADCA_CAL    [61994]
**         User handling procedure     : not specified
**         Number of conversions       : 1
**         AD resolution               : 12-bit
**
**         Input pins
**
**
**         Initialization:
**              Conversion             : Enabled
**              Event                  : Enabled
**         High speed mode
**             Prescaler               : divide-by-62
**     Contents  :
**         Measure    - byte BATT_Measure(bool WaitForResult);
**         GetValue16 - byte BATT_GetValue16(word *Values);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE BATT. */

#include "BATT.h"

#define IDLE            0              /* IDLE state           */
#define MEASURE         1              /* MESURE state         */
#define CONTINUOUS      2              /* CONTINUOUS state     */
#define SINGLE          3              /* SINGLE state         */

static bool OutFlg;                    /* Measurement finish flag */
/*lint -esym(765,BATT_ModeFlg) Disable MISRA rule (23) checking for symbols (BATT_ModeFlg). */
volatile byte BATT_ModeFlg;            /* Current state of device */

/*
** ===================================================================
**     Method      :  MainMeasure (component ADC)
**
**     Description :
**         The method performs A/D conversion(s). The method is called 
**         automatically as a part of measure methods or the HWEnDi 
**         method.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void MainMeasure(void)
{
  if (getRegBit(ADCA_ADSTAT,EOSI)) {   /* Is a scan cycle completed? */
    setRegBits(ADCA_ADSTAT,2048);      /* Clear EOSI flag */
    OutFlg = TRUE;                     /* Measured values are available */
    BATT_ModeFlg = IDLE;               /* Set the bean to the idle mode */
  }
}

/*
** ===================================================================
**     Method      :  HWEnDi (component ADC)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the bean.
**         The method is called automatically as a part of Enable, 
**         Disable and Init methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void)
{
  if (BATT_ModeFlg) {                  /* Launch measurement? */
    OutFlg = FALSE;                    /* Measured values are available */
    setRegBits(ADCA_ADSTAT,2048);      /* Clear flag */
    clrRegBit(ADCA_ADCR1,STOP);        /* Normal operation mode */
    setRegBit(ADCA_ADCR1,START);       /* Launching of conversion */
  }
  else {
    setRegBit(ADCA_ADCR1,STOP);        /* Stop command issued */
  }
}

/*
** ===================================================================
**     Method      :  BATT_Measure (component ADC)
**
**     Description :
**         This method performs one measurement on all channels that
**         are set in the bean inspector. (Note: If the <number of
**         conversions> is more than one the conversion of A/D channels
**         is performed specified number of times.)
**     Parameters  :
**         NAME            - DESCRIPTION
**         WaitForResult   - Wait for a result of a
**                           conversion. If <interrupt service> is
**                           disabled, A/D peripheral doesn't support
**                           measuring all channels at once or Autoscan
**                           mode property isn't enabled and at the same
**                           time the <number of channel> is greater
**                           than 1, then the WaitForResult parameter is
**                           ignored and the method waits for each
**                           result every time. If the <interrupt
**                           service> is disabled and a <number of
**                           conversions> is greater than 1, the
**                           parameter is ignored and the method also
**                           waits for each result every time.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already running
** ===================================================================
*/
byte BATT_Measure(bool WaitForResult)
{
  if (BATT_ModeFlg != IDLE) {          /* Is the device in running mode? */
    return ERR_BUSY;                   /* If yes then error */
  }
  BATT_ModeFlg = MEASURE;              /* Set state of device to the measure mode */
  HWEnDi();                            /* Enable the device */
  if (WaitForResult) {                 /* Is WaitForResult TRUE? */
    while (BATT_ModeFlg == MEASURE) {  /* Calling MainMeasure while IDLE state occured */
      MainMeasure();                   /* A/D converter handler */
    }
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  BATT_GetValue16 (component ADC)
**
**     Description :
**         This method returns the last measured values of all channels
**         justified to the left. Compared with <GetValue> method this
**         method returns more accurate result if the <number of
**         conversions> is greater than 1 and <AD resolution> is less
**         than 16 bits. In addition, the user code dependency on <AD
**         resolution> is eliminated.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Values          - Pointer to the array that contains
**                           the measured data.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_OVERRUN - External trigger overrun flag
**                           was detected after the last value(s) was
**                           obtained (for example by GetValue). This
**                           error may not be supported on some CPUs
**                           (see generated code).
** ===================================================================
*/
byte BATT_GetValue16(word *Values)
{
  if (BATT_ModeFlg != IDLE) {          /* Is the device in any measure mode? */
    MainMeasure();                     /* Call A/D converter handler */
  }
  if (!OutFlg) {                       /* Is measured value(s) available? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
  *Values = (getReg(ADCA_ADRSLT0) + 0) << 1; /* Store value from result register of device to user buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  BATT_Init (component ADC)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void BATT_Init(void)
{
  volatile word i;

  OutFlg = FALSE;                      /* No measured value */
  BATT_ModeFlg = IDLE;                 /* Device isn't running */
  /* ADCA_ADCR1: ??=0,STOP=1,START=0,SYNC=0,EOSIE=0,ZCIE=0,LLMTIE=0,HLMTIE=0,CHNCFG=0,??=0,SMODE=0 */
  setReg(ADCA_ADCR1,16384);            /* Set control register 1 */
  /* ADCA_ADPOWER: ??=0,??=0,??=0,PSTS2=0,PSTS1=0,PSTS0=0,PUDELAY=13,PSM=0,PD2=0,PD1=0,PD0=1 */
  setReg(ADCA_ADPOWER,209);            /* Enable device */
  /* ADCA_ADOFS0: ??=0,OFFSET=0,??=0,??=0,??=0 */
  setReg(ADCA_ADOFS0,0);               /* Set offset reg. 0 */
  /* ADCA_ADHLMT0: ??=0,HLMT=4095,??=0,??=0,??=0 */
  setReg(ADCA_ADHLMT0,32760);          /* Set high limit reg. 0 */
  /* ADCA_ADLLMT0: ??=0,LLMT=0,??=0,??=0,??=0 */
  setReg(ADCA_ADLLMT0,0);              /* Set low limit reg. 0 */
  /* ADCA_ADZCSTAT: ??=1,??=1,??=1,??=1,??=1,??=1,??=1,??=1,ZCS7=1,ZCS6=1,ZCS5=1,ZCS4=1,ZCS3=1,ZCS2=1,ZCS1=1,ZCS0=1 */
  setReg(ADCA_ADZCSTAT,65535);         /* Clear zero crossing status flags */
  /* ADCA_ADLSTAT: HLS7=1,HLS6=1,HLS5=1,HLS4=1,HLS3=1,HLS2=1,HLS1=1,HLS0=1,LLS7=1,LLS6=1,LLS5=1,LLS4=1,LLS3=1,LLS2=1,LLS1=1,LLS0=1 */
  setReg(ADCA_ADLSTAT,65535);          /* Clear high and low limit status */
  /* ADCA_ADSTAT: CIP=0,??=0,??=0,??=0,EOSI=1,ZCI=0,LLMTI=0,HLMTI=0,RDY7=0,RDY6=0,RDY5=0,RDY4=0,RDY3=0,RDY2=0,RDY1=0,RDY0=0 */
  setReg(ADCA_ADSTAT,2048);            /* Clear EOSI flag */
  /* ADCA_ADSDIS: TEST=0,??=0,??=0,??=0,??=0,??=0,??=0,DS7=1,DS6=1,DS5=1,DS4=1,DS3=1,DS2=1,DS1=1,DS0=0 */
  setReg(ADCA_ADSDIS,254);             /* Enable/disable of samples */
  /* ADCA_ADLST1: ??=0,SAMPLE3=0,??=0,SAMPLE2=0,??=0,SAMPLE1=0,??=0,SAMPLE0=7 */
  setReg(ADCA_ADLST1,7);               /* Set ADC channel list reg. */
  /* ADCA_ADZCC: ZCE7=0,ZCE6=0,ZCE5=0,ZCE4=0,ZCE3=0,ZCE2=0,ZCE1=0,ZCE0=0 */
  setReg(ADCA_ADZCC,0);                /* Set zero crossing control reg. */
  /* ADCA_ADCR2: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,DIV=30 */
  setReg(ADCA_ADCR2,30);               /* Set prescaler */
  for (i=0;i<100;i++) {}               /* Recovery time of voltage reference */
  while (ADCA_ADPOWER&((ADCA_ADPOWER_PSTS1_MASK|ADCA_ADPOWER_PSTS2_MASK))) {} /* Wait for device powered up */
}

/* END BATT. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
