/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : HMI_SPI.C
**     Project   : CyberNT3
**     Processor : 56F8366
**     Component : SWSPI
**     Version   : Component 01.018, Driver 01.15, CPU db: 2.87.042
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2011/8/20, 22:03
**     Abstract  :
**          This bean implements an external SPI communication interface specialy 
**          designed for SPI compatible beans. The interface uses three general-purpose 
**          I/O pins, first for the Input line, second for the Output line, third for 
**          the Serial Clock line. Is supported only Master mode with MSB first 
**          communication. 
**     Contents  :
**         RecvChar - byte HMI_SPI_RecvChar(byte *Chr);
**         SendChar - byte HMI_SPI_SendChar(byte Chr);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


/* MODULE HMI_SPI. */

#include "HMI_SPI.h"


#define OVERRUN_ERR  1                 /* Overrun error flag bit   */
#define CHAR_IN_RX   8                 /* Char is in RX buffer     */

static byte CLKshift;
static byte CLKsampl;
static byte InputBuffer;
static byte SerFlag;                   /* Flags for serial communication */
                                       /* Bits: 0 - OverRun error */
                                       /*       1 - Unused */
                                       /*       2 - Unused */
                                       /*       3 - Char in RX buffer */
                                       /*       4 - Unused */
                                       /*       5 - Unused */
                                       /*       6 - Unused */
                                       /*       7 - Unused */

/*
** ===================================================================
**     Method      :  HMI_SPI_RecvChar (component SWSPI)
**
**     Description :
**         If any data received, this method returns one character,
**         otherwise it returns error code (it does not wait for
**         data).
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - Pointer to received character.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_RXEMPTY - No data in receiver
**                           ERR_OVERRUN - Overrun error is detected
** ===================================================================
*/
byte HMI_SPI_RecvChar(byte *Chr)
{
  if(!(SerFlag & CHAR_IN_RX)) {        /* Is char. received */
    return ERR_RXEMPTY;
  }
  *Chr = InputBuffer;                  /* Store the character */
  if(SerFlag & OVERRUN_ERR) {          /* Is "overrun" occured? */
    SerFlag &= ~(OVERRUN_ERR|CHAR_IN_RX); /* If yes, clear flags */
    return ERR_OVERRUN;                /* ... and return error */
  }
  else {
    SerFlag &= ~CHAR_IN_RX;            /* If no, clear flag */
    return ERR_OK;                     /* ... and return */
  }
}

/*
** ===================================================================
**     Method      :  HMI_SPI_SendChar (component SWSPI)
**
**     Description :
**         Send one character to the channel.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/
byte HMI_SPI_SendChar(byte Chr)
{
  byte i;
  for(i=0; i<8; i++) {
    Inhr2_PutVal((bool)(Chr & 128));   /* Set value on MOSI */
    InputBuffer <<= 1;
    Inhr3_PutVal(CLKsampl);            /* Set CLK to sample value */
    InputBuffer += Inhr1_GetVal()?1:0; /* Read value from MISO */
    Chr <<= 1;
    Inhr3_PutVal(CLKshift);            /* Set CLK to shift value */
  }
  Inhr2_PutVal(1);                     /* Set value on MOSI */
  if(SerFlag & CHAR_IN_RX) {           /* Is char. received? */
    SerFlag |= OVERRUN_ERR;            /* If yes then set "overrun" flag */
  }
  else {
    SerFlag |= CHAR_IN_RX;             /* If no then set "char in Rx" flag */
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  HMI_SPI_Init (component SWSPI)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void HMI_SPI_Init(void)
{
  CLKsampl = 1;                        /* Set sample value to 1 */
  CLKshift = 0;                        /* Set shift value to 0 */
  Inhr3_PutVal((bool)0);               /* Set CLK to idle value */
  Inhr2_PutVal((bool)1);               /* Set value on MOSI */
  SerFlag = 0;                         /* Clear flags */
}


/* END HMI_SPI. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/

