/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : HMI_KEY.C
**     Project   : CyberNT3
**     Processor : 56F8366
**     Component : ADC
**     Version   : Component 01.580, Driver 02.05, CPU db: 2.87.042
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2011/8/20, 22:03
**     Abstract  :
**         This device "ADC" implements an A/D converter,
**         its control methods and interrupt/event handling procedure.
**     Settings  :
**         AD control register         : ADCB_ADCR1  [62016]
**         AD control register         : ADCB_ADCR2  [62017]
**         AD control register         : ADCB_ADZCC  [62018]
**         AD control register         : ADCB_ADLST1 [62019]
**         AD control register         : ADCB_ADLST2 [62020]
**         AD control register         : ADCB_ADSDIS [62021]
**         AD control register         : ADCB_ADSTAT [62022]
**         AD control register         : ADCB_ADLSTAT [62023]
**         AD control register         : ADCB_ADZCSTAT [62024]
**         AD control register         : ADCB_ADLLMT0 [62033]
**         AD control register         : ADCB_ADLLMT1 [62034]
**         AD control register         : ADCB_ADLLMT2 [62035]
**         AD control register         : ADCB_ADLLMT3 [62036]
**         AD control register         : ADCB_ADLLMT4 [62037]
**         AD control register         : ADCB_ADLLMT5 [62038]
**         AD control register         : ADCB_ADLLMT6 [62039]
**         AD control register         : ADCB_ADLLMT7 [62040]
**         AD control register         : ADCB_ADHLMT0 [62041]
**         AD control register         : ADCB_ADHLMT1 [62042]
**         AD control register         : ADCB_ADHLMT2 [62043]
**         AD control register         : ADCB_ADHLMT3 [62044]
**         AD control register         : ADCB_ADHLMT4 [62045]
**         AD control register         : ADCB_ADHLMT5 [62046]
**         AD control register         : ADCB_ADHLMT6 [62047]
**         AD control register         : ADCB_ADHLMT7 [62048]
**         AD control register         : ADCB_ADOFS0 [62049]
**         AD control register         : ADCB_ADOFS1 [62050]
**         AD control register         : ADCB_ADOFS2 [62051]
**         AD control register         : ADCB_ADOFS3 [62052]
**         AD control register         : ADCB_ADOFS4 [62053]
**         AD control register         : ADCB_ADOFS5 [62054]
**         AD control register         : ADCB_ADOFS6 [62055]
**         AD control register         : ADCB_ADOFS7 [62056]
**         AD control register         : ADCB_ADPOWER [62057]
**         AD control register         : ADCB_CAL    [62058]
**         User handling procedure     : not specified
**         Number of conversions       : 1
**         AD resolution               : 12-bit
**
**         Input pins
**
**
**
**         Initialization:
**              Conversion             : Enabled
**              Event                  : Enabled
**         High speed mode
**             Prescaler               : divide-by-62
**     Contents  :
**         Measure    - byte HMI_KEY_Measure(bool WaitForResult);
**         GetValue16 - byte HMI_KEY_GetValue16(word *Values);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE HMI_KEY. */

#include "HMI_KEY.h"

#define IDLE            0              /* IDLE state           */
#define MEASURE         1              /* MESURE state         */
#define CONTINUOUS      2              /* CONTINUOUS state     */
#define SINGLE          3              /* SINGLE state         */

static bool OutFlg;                    /* Measurement finish flag */
/*lint -esym(765,HMI_KEY_ModeFlg) Disable MISRA rule (23) checking for symbols (HMI_KEY_ModeFlg). */
volatile byte HMI_KEY_ModeFlg;         /* Current state of device */

/*
** ===================================================================
**     Method      :  MainMeasure (component ADC)
**
**     Description :
**         The method performs A/D conversion(s). The method is called 
**         automatically as a part of measure methods or the HWEnDi 
**         method.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void MainMeasure(void)
{
  if (getRegBit(ADCB_ADSTAT,EOSI)) {   /* Is a scan cycle completed? */
    setRegBits(ADCB_ADSTAT,2048);      /* Clear EOSI flag */
    OutFlg = TRUE;                     /* Measured values are available */
    HMI_KEY_ModeFlg = IDLE;            /* Set the bean to the idle mode */
  }
}

/*
** ===================================================================
**     Method      :  HWEnDi (component ADC)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the bean.
**         The method is called automatically as a part of Enable, 
**         Disable and Init methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void)
{
  if (HMI_KEY_ModeFlg) {               /* Launch measurement? */
    OutFlg = FALSE;                    /* Measured values are available */
    setRegBits(ADCB_ADSTAT,2048);      /* Clear flag */
    clrRegBit(ADCB_ADCR1,STOP);        /* Normal operation mode */
    setRegBit(ADCB_ADCR1,START);       /* Launching of conversion */
  }
  else {
    setRegBit(ADCB_ADCR1,STOP);        /* Stop command issued */
  }
}

/*
** ===================================================================
**     Method      :  HMI_KEY_Measure (component ADC)
**
**     Description :
**         This method performs one measurement on all channels that
**         are set in the bean inspector. (Note: If the <number of
**         conversions> is more than one the conversion of A/D channels
**         is performed specified number of times.)
**     Parameters  :
**         NAME            - DESCRIPTION
**         WaitForResult   - Wait for a result of a
**                           conversion. If <interrupt service> is
**                           disabled, A/D peripheral doesn't support
**                           measuring all channels at once or Autoscan
**                           mode property isn't enabled and at the same
**                           time the <number of channel> is greater
**                           than 1, then the WaitForResult parameter is
**                           ignored and the method waits for each
**                           result every time. If the <interrupt
**                           service> is disabled and a <number of
**                           conversions> is greater than 1, the
**                           parameter is ignored and the method also
**                           waits for each result every time.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already running
** ===================================================================
*/
byte HMI_KEY_Measure(bool WaitForResult)
{
  if (HMI_KEY_ModeFlg != IDLE) {       /* Is the device in running mode? */
    return ERR_BUSY;                   /* If yes then error */
  }
  HMI_KEY_ModeFlg = MEASURE;           /* Set state of device to the measure mode */
  HWEnDi();                            /* Enable the device */
  if (WaitForResult) {                 /* Is WaitForResult TRUE? */
    while (HMI_KEY_ModeFlg == MEASURE) { /* Calling MainMeasure while IDLE state occured */
      MainMeasure();                   /* A/D converter handler */
    }
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  HMI_KEY_GetValue16 (component ADC)
**
**     Description :
**         This method returns the last measured values of all channels
**         justified to the left. Compared with <GetValue> method this
**         method returns more accurate result if the <number of
**         conversions> is greater than 1 and <AD resolution> is less
**         than 16 bits. In addition, the user code dependency on <AD
**         resolution> is eliminated.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Values          - Pointer to the array that contains
**                           the measured data.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_OVERRUN - External trigger overrun flag
**                           was detected after the last value(s) was
**                           obtained (for example by GetValue). This
**                           error may not be supported on some CPUs
**                           (see generated code).
** ===================================================================
*/
byte HMI_KEY_GetValue16(word *Values)
{
  if (HMI_KEY_ModeFlg != IDLE) {       /* Is the device in any measure mode? */
    MainMeasure();                     /* Call A/D converter handler */
  }
  if (!OutFlg) {                       /* Is measured value(s) available? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
  *Values++ = (getReg(ADCB_ADRSLT0) + 0) << 1; /* Store value from result register of device to user buffer */
  *Values = (getReg(ADCB_ADRSLT1) + 0) << 1; /* Store value from result register of device to user buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  HMI_KEY_Init (component ADC)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void HMI_KEY_Init(void)
{
  volatile word i;

  OutFlg = FALSE;                      /* No measured value */
  HMI_KEY_ModeFlg = IDLE;              /* Device isn't running */
  /* ADCB_ADCR1: ??=0,STOP=1,START=0,SYNC=0,EOSIE=0,ZCIE=0,LLMTIE=0,HLMTIE=0,CHNCFG=0,??=0,SMODE=0 */
  setReg(ADCB_ADCR1,16384);            /* Set control register 1 */
  /* ADCB_ADPOWER: ??=0,??=0,??=0,PSTS2=0,PSTS1=0,PSTS0=0,PUDELAY=13,PSM=0,PD2=0,PD1=0,PD0=1 */
  setReg(ADCB_ADPOWER,209);            /* Enable device */
  /* ADCB_ADOFS0: ??=0,OFFSET=0,??=0,??=0,??=0 */
  setReg(ADCB_ADOFS0,0);               /* Set offset reg. 0 */
  /* ADCB_ADOFS1: ??=0,OFFSET=0,??=0,??=0,??=0 */
  setReg(ADCB_ADOFS1,0);               /* Set offset reg. 1 */
  /* ADCB_ADHLMT0: ??=0,HLMT=4095,??=0,??=0,??=0 */
  setReg(ADCB_ADHLMT0,32760);          /* Set high limit reg. 0 */
  /* ADCB_ADHLMT1: ??=0,HLMT=4095,??=0,??=0,??=0 */
  setReg(ADCB_ADHLMT1,32760);          /* Set high limit reg. 1 */
  /* ADCB_ADLLMT0: ??=0,LLMT=0,??=0,??=0,??=0 */
  setReg(ADCB_ADLLMT0,0);              /* Set low limit reg. 0 */
  /* ADCB_ADLLMT1: ??=0,LLMT=0,??=0,??=0,??=0 */
  setReg(ADCB_ADLLMT1,0);              /* Set low limit reg. 1 */
  /* ADCB_ADZCSTAT: ??=1,??=1,??=1,??=1,??=1,??=1,??=1,??=1,ZCS7=1,ZCS6=1,ZCS5=1,ZCS4=1,ZCS3=1,ZCS2=1,ZCS1=1,ZCS0=1 */
  setReg(ADCB_ADZCSTAT,65535);         /* Clear zero crossing status flags */
  /* ADCB_ADLSTAT: HLS7=1,HLS6=1,HLS5=1,HLS4=1,HLS3=1,HLS2=1,HLS1=1,HLS0=1,LLS7=1,LLS6=1,LLS5=1,LLS4=1,LLS3=1,LLS2=1,LLS1=1,LLS0=1 */
  setReg(ADCB_ADLSTAT,65535);          /* Clear high and low limit status */
  /* ADCB_ADSTAT: CIP=0,??=0,??=0,??=0,EOSI=1,ZCI=0,LLMTI=0,HLMTI=0,RDY7=0,RDY6=0,RDY5=0,RDY4=0,RDY3=0,RDY2=0,RDY1=0,RDY0=0 */
  setReg(ADCB_ADSTAT,2048);            /* Clear EOSI flag */
  /* ADCB_ADSDIS: TEST=0,??=0,??=0,??=0,??=0,??=0,??=0,DS7=1,DS6=1,DS5=1,DS4=1,DS3=1,DS2=1,DS1=0,DS0=0 */
  setReg(ADCB_ADSDIS,252);             /* Enable/disable of samples */
  /* ADCB_ADLST1: ??=0,SAMPLE3=0,??=0,SAMPLE2=0,??=0,SAMPLE1=6,??=0,SAMPLE0=5 */
  setReg(ADCB_ADLST1,101);             /* Set ADC channel list reg. */
  /* ADCB_ADZCC: ZCE7=0,ZCE6=0,ZCE5=0,ZCE4=0,ZCE3=0,ZCE2=0,ZCE1=0,ZCE0=0 */
  setReg(ADCB_ADZCC,0);                /* Set zero crossing control reg. */
  /* ADCB_ADCR2: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,DIV=30 */
  setReg(ADCB_ADCR2,30);               /* Set prescaler */
  for (i=0;i<100;i++) {}               /* Recovery time of voltage reference */
  while (ADCB_ADPOWER&((ADCB_ADPOWER_PSTS1_MASK|ADCB_ADPOWER_PSTS2_MASK))) {} /* Wait for device powered up */
}

/* END HMI_KEY. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
