/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : HMI_BUZZ.C
**     Project   : CyberNT3
**     Processor : 56F8366
**     Component : PWM
**     Version   : Component 02.221, Driver 02.02, CPU db: 2.87.042
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2011/8/20, 22:03
**     Abstract  :
**         This bean implements a pulse-width modulation generator
**         that generates signal with variable duty and fixed cycle. 
**     Settings  :
**         Used output pin             : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       70            |  PWMA5
**             ----------------------------------------------------
**
**         Timer name                  : PWM_A [15-bit]
**         Counter                     : PWMA_PMCNT [61764]
**         Mode register               : PWMA_PMCTL [61760]
**         Run register                : PWMA_PMCTL [61760]
**         Prescaler                   : PWMA_PMCTL [61760]
**         Compare register            : PWMA_PWMVAL5 [61771]
**         Flip-flop register          : PWMA_PMCFG [61775]
**
**         User handling procedure     : not specified
**
**
**         Initialization:
**              Output level           : high
**              Timer                  : Enabled
**              Event                  : Enabled
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 10000000 Hz
**           Initial value of            period     pulse width
**             Xtal ticks              : 24672      1
**             microseconds            : 3084       0
**             milliseconds            : 3          0
**             seconds (real)          : 0.003084   0.0000001
**
**     Contents  :
**         SetRatio16 - byte HMI_BUZZ_SetRatio16(word Ratio);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


/* MODULE HMI_BUZZ. */

#include "HMI_BUZZ.h"

static word RatioStore;                /* Ratio of L-level to H-level */

/* Internal method prototypes */
static void SetRatio(void);

#define SetPV(Val) setRegBitGroup(PWMA_PMCTL,PRSC,(Val))

/*
** ===================================================================
**     Method      :  SetRatio (component PWM)
**
**     Description :
**         Calculates and sets new duty ratio. The method is called 
**         automatically as a part of several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void SetRatio(void)
{
  setReg(PWMA_PWMVAL5,((getReg(PWMA_PWMCM)+1) * (dword)RatioStore) >> 16); /* Calculate new value according to the given ratio */
  setRegBit(PWMA_PMCTL,LDOK);          /* Load counter and modulo registers into buffers */
}
/*
** ===================================================================
**     Method      :  HMI_BUZZ_SetRatio16 (component PWM)
**
**     Description :
**         This method sets a new duty-cycle ratio.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Ratio      - Ratio is expressed as an 16-bit unsigned integer
**                      number. 0 - 65535 value is proportional
**                      to ratio 0 - 100%
**         Note: Calculated duty depends on the timer possibilities
**               and on the selected period.
**     Returns     :
**         ---        - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte HMI_BUZZ_SetRatio16(word Ratio)
{
  RatioStore = Ratio;                  /* Store new value of the ratio */
  SetRatio();                          /* Calculate and set up new appropriate duty value */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  HMI_BUZZ_Init (component PWM)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void HMI_BUZZ_Init(void)
{
  RatioStore = (word)2U;               /* Store initial value of the ratio */
  /* PWMA_PMICCR: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,ICC2=0,ICC1=0,ICC0=0 */
  setReg(PWMA_PMICCR,0);               /* Set up Internal Correction Control Register */
  /* PWMA_PMDISMAP1: DISMAP=0 */
  setReg(PWMA_PMDISMAP1,0);            /* Set up PWM Disable Mapping Register 1 */
  /* PWMA_PMDISMAP2: DISMAP=0 */
  setReg(PWMA_PMDISMAP2,0);            /* Set up PWM Disable Mapping Register 2 */
  /* PWMA_PMOUT: PAD_EN=0,??=0,OUTCTL=63,??=0,??=0,OUT=63 */
  setReg(PWMA_PMOUT,16191);            /* Set up Output Control Register */
  setReg(PWMA_PMDEADTM,0);             /* Set up Dead-Time Register */
  /* PWMA_PMCCR: ENHA=0,nBX=0,MSK=63,??=0,??=0,VLMODE=0,??=0,SWP45=0,SWP23=0,SWP01=0 */
  setReg(PWMA_PMCCR,16128);            /* Set up PWM Chanel Control Register */
  /* PWMA_PMCFG: ??=0,DBG_EN=0,WAIT_EN=0,EDG=1,??=0,TOPNEG45=0,TOPNEG23=0,TOPNEG01=0,??=0,BOTNEG45=0,BOTNEG23=0,BOTNEG01=0,INDEP45=1,INDEP23=1,INDEP01=1,WP=0 */
  setReg(PWMA_PMCFG,4110);             /* Set up PWM configure register */
  setReg(PWMA_PMCNT,0);                /* Reset counter */
  setReg(PWMA_PWMVAL5,1);              /* Store initial value to the duty-compare register */
  setReg(PWMA_PWMCM,30840);            /* and to the period register */
  SetPV((byte)3);                      /* Set prescaler register according to the selected high speed CPU mode */
}

/* END HMI_BUZZ. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
