/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : LEFTPA.H
**     Project   : CyberNT3
**     Processor : 56F8366
**     Component : PulseAccumulator
**     Version   : Component 01.183, Driver 02.03, CPU db: 2.87.042
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2011/8/20, 22:03
**     Abstract  :
**          Pulse accumulator decodes the primary and secondary external inputs as
**          quadrature encoded signals. Quadrature signals are usually generated by
**          rotary or linear sensors used to monitor movement of motor shafts or
**          mechanical equipment.
**     Settings  :
**             Pulse accumulator       : TMRA3_PACNT
**
**
**         Mode                        : Quadrature
**
**         Initialization:
**              Pulse accumulator      : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : TMRA3_CNTR [61557]
**              Hold                   : TMRA3_HOLD [61556]
**              Run                    : TMRA3_CTRL [61558]
**              Prescaler              : TMRA3_CTRL [61558]
**
**         User handling procedure     : not specified
**
**     Contents  :
**         GetCounterValue  - void LEFTPA_GetCounterValue(word *Value);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __LEFTPA
#define __LEFTPA

/* MODULE LEFTPA. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "PE_Timer.h"
#include "Cpu.h"

#ifndef __BWUserType_LEFTPA_TCounterValue
#define __BWUserType_LEFTPA_TCounterValue
  typedef word LEFTPA_TCounterValue;   /* Counter value, width depend on on selected peripheal. */
#endif


void LEFTPA_GetCounterValue(LEFTPA_TCounterValue *Value);
/*
** ===================================================================
**     Method      :  LEFTPA_GetCounterValue (component PulseAccumulator)
**
**     Description :
**         This method returns the content of the pulse accumulator
**         counter.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Value           - Pointer to returned value. [Note:]
**                           Parameter type depends on the width of the
**                           selected counter (may be 8, 16, 32 or 64
**                           bits long). See the method prototype in the
**                           generated module.
**     Returns     : Nothing
** ===================================================================
*/

void LEFTPA_Init(void);
/*
** ===================================================================
**     Method      :  LEFTPA_Init (component PulseAccumulator)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

/* END LEFTPA. */

#endif /* ifndef __LEFTPA */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
